### ISSUE TITLE
Unable to load formatted value for associateidentitytypecode

### ISSUE THREAD

**Issue by mortenbested** [jamesnovak/XrmDocumentTemplateManager#5]
I am getting this error when trying to connect Document Template Manager to one of my environments.

Error:

**Unable to load formatted value for associateidentitytypecode**

Stack trace:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Futurez.Xrm.Tools.DocTemplateManagerControl.LoadTemplatesComplete(List`1 templates)
   at Futurez.Xrm.Tools.DocTemplateManagerControl.<>c__DisplayClass7_0.<LoadDocumentTemplates>b__2(RunWorkerCompletedEventArgs e)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by mortenbested** [comment]
Hi @MscrmTools

Here is a screenshot (doesn't provide much extra details, but nonetheless):
![image](https://user-images.githubusercontent.com/7370870/203273001-dda278c6-1467-4ece-8df7-4b98a6fc76ab.png)

I use version 1.2022.11.3

My guess is there is a "broken/bad" template in our environments (we have lots of document templates, around ~500 templates). It would be really nice if the plugin was able to handle a "bad" template my skipping it or something.

I will try to clone the code an run it against our environments to identify the root cause.

**Comment by MscrmTools** [comment]
Ah ok, you made a typo mistake for the faulty attribute. That is why I did not find any reference to it

**Comment by ralphcorrigan** [comment]
Hi, sorry to bump this after quite a while but I'm getting exactly the same problem (and the plugin won't load). I've used it before many times, but in a new work location it fails with this message in all environments. Did anything come of resolving it?
Thanks

**Comment by markabjunior** [comment]
I am having the same issue.

**Comment by MscrmTools** [comment]
@markabjunior can you tell me if your instance uses multiple languages? If so, can you check if all tables involved in a template have a proper display name for the language you are using?
I see where the issue comes from but it shouldn't happen at all or happen for everybody which is not the case

**Comment by MscrmTools** [comment]
@ralphcorrigan can you try with this version?

[Futurez.Xrm.Tools.DocTemplateManager.zip](https://github.com/jamesnovak/XrmDocumentTemplateManager/files/13301279/Futurez.Xrm.Tools.DocTemplateManager.zip)

**Comment by markabjr** [comment]
That worked, thank you very much guys.

**Comment by MscrmTools** [comment]
@markabjr Can you tell me if any template in the liste shows an associated table with a schema name instead of a display name?

**Comment by ralphcorrigan** [comment]
> @ralphcorrigan can you try with this version?
> 
> [Futurez.Xrm.Tools.DocTemplateManager.zip](https://github.com/jamesnovak/XrmDocumentTemplateManager/files/13301279/Futurez.Xrm.Tools.DocTemplateManager.zip)

Thanks for this - I had given up on there being a solution, but this works a treat!

**Comment by MscrmTools** [comment]
Yep, sorry it took so long to fix
